---
- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  tasks:
    - name: install java
      apt:
        name: default-jdk
        state: present

    - name: create a directore called tomcat
      file:
         path: /home/ansible/tomcat
         state: directory
         mode: '0777'

    - name: add tomcat group
      group:
         name: tomcat

    - name: add tomcat user
      user:
         name: tomcat
         group: tomcat
         home: /user/share/tomcat
         createhome: no

    - name: create /opt/tomcat directory
      file:
         path: /opt/tomcat
         state: directory
         mode: 0777

    - name: download the tar gz file and extract
      unarchive:
         src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.0-M4/bin/apache-tomcat-10.1.0-M4.tar.gz
         dest: /opt/tomcat/
         remote_src: yes
         extra_opts: [--strip-components=1]
         

         #    - name: unzip the downloaded file
         #    unarchive:
         #  src: /opt/tomcat/apache-tomcat-10.1.0-M4.tar.gz
         # dest: /opt/tomcat/
         #  remote_src: yes

         #    - name: change ownership of downloaded files
         #      shell: 
         #         cmd: chown -R ansible /home/ansible/tomcat/
         #
    - name: Change ownership
      file:
         path: /opt/tomcat
         owner: tomcat
         group: tomcat
         mode: "u+rwx,g+rx,o=rx"
         recurse: yes
         state: directory

    - name: Copy Tomcat service from local to remote
      copy:
        src: /home/ansible/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755

    - name: copying file to webapps directory
      shell:
         cmd: cp /home/ansible/example/addressbook.war /opt/tomcat/webapps/

    - name: Start and enable Tomcat service
      systemd:
         name: tomcat
         state: started
         enabled: true
         daemon_reload: true

         #    - name: start tomcat server
         # shell: 
         # cmd: /home/ansible/tomcat/apache-tomcat-10.1.0-M4/bin/startup.sh


