---
- hosts: webservers
  remote_user: ansible
  become: yes
  tasks:
    - name: installs everything
      apt:
        name: tomcat9
        state: latest

    - name: copy the war file
      shell:
         cmd: cp /home/ansible/example/addressbook.war /var/lib/tomcat9/webapps/

    - name: start the tomcat service
      systemd:
          name: tomcat9
          state: started
          enabled: true
          daemon_reload: true
